### ISSUE TITLE
Separate view data in quest data classes

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2494]
### Task
For the cycleway quest, the cycleway answer options are cleanly seperated into two files: [`Cycleway.kt`](https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/Cycleway.kt) contains the "pure data" (the enum) and [`CyclewayItem`](https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/CyclewayItem.kt) contains the view-related part of a cycleway answer option.

This is better than how it is done for for example the surface quest (and others). There, in [`Surface.kt`](https://github.com/streetcomplete/StreetComplete/blob/25d0984bcedc5d4daf617486f2c71d22dbc03633/app/src/main/java/de/westnordost/streetcomplete/quests/surface/Surface.kt), the enum is not pure data because it contains reference to Android-specific view stuff. So for these quest(s), the data class should be refactored to be like for the cycleway class. 

### Example

So it should be....
```kotlin
enum class Surface(val value: String) { // or osmValue?
  ASPHALT("asphalt"),
  // etc....
}

// in SurfaceItem.kt
fun Surface.asItem(): Item<Surface> {
   // ... well, see CyclewayItem.kt, ...
}
```

### Reason
Apart from it being good style generally to seperate UI from data logic, it is a step towards making #1892 or any other port from Android to something else a little less work to do.

### Quests where this "old style" is used
- BuildingType
- Surface

### And then
And there is more. Quest types should no longer have a `String` as parameter but an enum. 

Compare [`AddRecyclingTypeForm`](https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/quests/recycling/AddRecyclingTypeForm.kt#L11-L13) (new style) with [`AddRailwayCrossingBarrier`](https://github.com/streetcomplete/StreetComplete/blob/cc7624d2f8c83c037f4a078eb56dadd3b1cd80a2/app/src/main/java/de/westnordost/streetcomplete/quests/railway_crossing/AddRailwayCrossingBarrierForm.kt#L10-L13) (old style). It is okay for the enum to define an OSM value like in the example with surface above.

**Comment by westnordost** [comment]
Maybe you are interested in helping out here, @FloEdelmann

**Comment by FloEdelmann** [comment]
These are all the quest forms which extend from `AImageListQuestAnswerFragment` and have `String` instead of an enum as a parameter:

- [ ] [`AddBikeParkingTypeForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bike_parking_type/AddBikeParkingTypeForm.kt)
- [ ] [`AddBridgeStructureForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bridge_structure/AddBridgeStructureForm.kt)
- [ ] [`AddCrossingTypeForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/crossing_type/AddCrossingTypeForm.kt)
- [ ] [`AddFireHydrantTypeForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/fire_hydrant/AddFireHydrantTypeForm.kt)
- [ ] [`AddKerbHeightForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/kerb_height/AddKerbHeightForm.kt)
- [ ] [`AddForestLeafTypeForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/leaf_detail/AddForestLeafTypeForm.kt)
- [ ] [`AddOrchardProduceForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/orchard_produce/AddOrchardProduceForm.kt)
- [ ] [`AddParkingTypeForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/parking_type/AddParkingTypeForm.kt)
- [ ] [`AddPowerPolesMaterialForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/powerpoles_material/AddPowerPolesMaterialForm.kt)
- [ ] [`AddRailwayCrossingBarrierForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/railway_crossing/AddRailwayCrossingBarrierForm.kt)
- [ ] [`AddReligionForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/religion/AddReligionForm.kt)
- [ ] [`AddRoofShapeForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/roof_shape/AddRoofShapeForm.kt)
- [ ] [`AddSportForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/sport/AddSportForm.kt)
- [ ] [`AddInformationForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/tourism_information/AddInformationForm.kt)
- [ ] [`AddTracktypeForm.kt`](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/tracktype/AddTracktypeForm.kt)
