### ISSUE TITLE
Add privacy-icons in the app intro and in the privacy policy 

### ISSUE THREAD

**Issue by tiptoptom** [streetcomplete/StreetComplete#5148]
**Use case**

[privacy-icons](https://privacy-icons.ch/) enable you to find out easily, quickly and clearly why which data about you is being processed. To add privacy-icons in the app intro would allow users to be informed transparently about how their data is being used.

**ToDo's**

- [ ] decision for or against privacy-icons
- [ ] assemble appropriate icons
- [ ] [register usage](https://privacy-icons.ch/kontakt/)
- [ ] implement

**Comment by thefeiter** [comment]
That is actually a quite nice Idea! These Icons offer a pretty good overview over the processed data.

You can even use the negative Icons to stress that you don't store/use a particular set of data.

**Comment by westnordost** [comment]
I am going to pass on this.

First of all, these icons are not well-known enough that they would be immediately recognized (like the CC licenses usually are) to be actually helpful.

Also, the privacy policy is meant to be read, written concise and to the point, without fluff and legal bla bla. So, it is unnecessary to provide a "human readable" version of the privacy policy, it would only make the whole thing longer in total and thus less likely people would actually read it.

Finally, regarding the idea of these icons in general, I am somewhat skeptical, because only rough categories are given, e.g. _"Standortdaten - Wir bearbeiten Ihre Standortdaten."_. StreetComplete does that, but the interesting question is **for what** and **with whom is this shared**? This is naturally not covered by the icons, yet this is exactly what the privacy policy should explain.

**Comment by tiptoptom** [comment]
> First of all, these icons are not well-known enough that they would be immediately recognized (like the CC licenses often are) to be actually helpful.

Yes, but that is the chicken-and-egg problem. 😄


I think such general icons can give a good first estimation (for example in the app intro) and arouse the interest to read the privacy policy for more details.


But all good, I can understand your arguments too.
